"""Rule admission report: how each rule behaves on a real tape before it is trusted.

Reports the three review groups, per-rule outcomes and behaviour on calibration examples.
Known-clean anchors must not have major root-cause findings; minor observations can remain.
High firing rates are diagnostic and require investigation, not automatic rule rejection.
Stable rule IDs preserve traceability independently of the public inspection groups.

    python scripts/admission.py data/loans.xlsx --clean 32271989 99981632 --seeded 37216892 \
        --markdown reports/rule_admission.md
"""

from __future__ import annotations

import argparse
import math
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from loan_dq.config import Config, ConfigError
from loan_dq.engine import AsOfError, TapeRejectedError, run
from loan_dq.io.reader import TapeReadError
from loan_dq.report.schema import Report
from loan_dq.rules.base import Rule, Severity, check_group
from loan_dq.rules.registry import all_rules


@dataclass
class RuleStats:
    rule: Rule
    fail: int
    passed: int
    not_evaluable: int
    fires_on: list[int]
    root_on: list[int]
    emitted: list[str]
    notes: list[str]
    rejected: bool = False

    @property
    def verdict(self) -> str:
        return "; ".join(self.notes) or "ok"


def admit(report: Report, clean: set[int], max_share: float, rules: list[Rule]) -> list[RuleStats]:
    n = len(report.loans) or 1
    status: dict[str, Counter[str]] = {r.id: Counter() for r in rules}
    fires_on: dict[str, set[int]] = {r.id: set() for r in rules}
    root_on: dict[str, set[int]] = {r.id: set() for r in rules}
    emitted: dict[str, set[str]] = {r.id: set() for r in rules}
    major_on: dict[str, set[int]] = {r.id: set() for r in rules}
    for loan in report.loans:
        for o in loan.rule_outcomes:
            if o.rule_id not in status:
                continue
            status[o.rule_id][o.status] += 1
            if o.status == "fail":
                fires_on[o.rule_id].add(loan.loan_id)
        for f in loan.findings:
            if f.rule_id not in emitted:
                continue
            emitted[f.rule_id].add(f.severity)
            if f.root_cause and f.severity != "info":
                root_on[f.rule_id].add(loan.loan_id)
            if f.root_cause and Severity(f.severity).rank >= Severity.MEDIUM.rank:
                major_on[f.rule_id].add(loan.loan_id)
    out: list[RuleStats] = []
    for rule in rules:
        s = status[rule.id]
        share = s["fail"] / n
        notes: list[str] = []
        hit_clean = sorted(major_on[rule.id] & clean)
        if hit_clean:
            notes.append(f"MAJOR FINDING ON CLEAN {hit_clean}")
        if share > max_share and rule.severity.value != "info":
            notes.append(
                f"diagnostic: fires on {share:.0%} of tape; investigate prevalence/conventions"
            )
        out.append(
            RuleStats(
                rule,
                s["fail"],
                s["pass"],
                s["not_evaluable"],
                sorted(fires_on[rule.id]),
                sorted(root_on[rule.id]),
                sorted(emitted[rule.id]),
                notes,
                rejected=bool(hit_clean),
            )
        )
    return out


def write_markdown(
    path: Path, report: Report, stats: list[RuleStats], clean: list[int], seeded: list[int]
) -> None:
    n = len(report.loans) or 1
    c = report.counts()
    lines = [
        "# Rule admission report",
        "",
        "Generated by `scripts/admission.py`; regenerate after any rule or threshold change.",
        "",
        f"- tape: `{report.input_file}` sha256 `{report.input_sha256}`",
        f"- ruleset `{report.ruleset_version}`, config digest `{report.config_digest}`, "
        f"as-of {report.as_of.isoformat()} ({report.as_of_source})",
        f"- loans {len(report.loans)}, quarantined rows {len(report.quarantined)}, "
        f"verdicts {c['by_verdict']}, severities {c['by_severity']}",
        f"- data_integrity {c['data_integrity']}, credit_event {c['credit_event']}, "
        f"partial coverage {c['partial_coverage']}",
        "",
        "## Three review groups",
        "",
        *[
            f"- **{g['label']}**: {g['rule_count']} {g['scope']} checks"
            for g in report.check_groups
        ],
        "",
        "Stable rule IDs identify individual checks, not additional processing layers.",
        "",
        "## What each rule did on this tape",
        "",
        "`fail` = rule fired; `root` = loans where it is the root cause of a non-info finding; "
        "`n/e` = not evaluable (incomplete evidence or not applicable, never a flag). "
        "Known-clean anchors must have no major root-cause findings. High fire share is "
        "diagnostic, not proof that a rule is wrong; minor observations do not reject a rule.",
        "",
        "| group | rule | severity | fail | root | pass | n/e | share | admitted | fires on |",
        "|---|---|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for s in stats:
        ids = ", ".join(str(i) for i in s.fires_on[:12])
        if len(s.fires_on) > 12:
            ids += f", … (+{len(s.fires_on) - 12})"
        group = check_group(s.rule.id)
        lines.append(
            f"| {group.label if group else '-'} | {s.rule.id} | {'/'.join(s.emitted) or '-'} | "
            f"{s.fail} | {len(s.root_on)} | {s.passed} | {s.not_evaluable} | "
            f"{s.fail / n:.0%} | {s.verdict} | {ids} |"
        )
    lines += ["", "## Calibration loans", ""]
    by_id = {r.loan_id: r for r in report.loans}
    for loan_id in clean:
        r = by_id.get(loan_id)
        line = (
            f"- `{loan_id}` known clean → **{r.verdict}** "
            f"({r.checks_passed} passed / {r.checks_failed} failed / "
            f"{r.checks_not_evaluable} not evaluable)"
            if r
            else f"- `{loan_id}` known clean → not in tape"
        )
        lines.append(line)
    for loan_id in seeded:
        r = by_id.get(loan_id)
        line = (
            f"- `{loan_id}` known irregular → **{r.verdict} {r.severity}**: {r.primary_reason}"
            if r
            else f"- `{loan_id}` known irregular → not in tape"
        )
        lines.append(line)
    lines += ["", "## Tape-level checks", ""]
    for t in report.tape_checks:
        lines.append(f"- {t.rule_id} **{t.status}**: {t.message}")
    lines += [
        "",
        "## Flagged loans",
        "",
        "| loan | severity | integrity | credit | root causes |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(report.loans, key=lambda x: x.row_index):
        if r.verdict != "flagged":
            continue
        roots = ", ".join(f.rule_id for f in r.findings if f.root_cause and f.severity != "info")
        lines.append(
            f"| {r.loan_id} | {r.severity} | {r.data_integrity} | {r.credit_event} | {roots} |"
        )
    lines += ["", "## Normal loans with minor observations", ""]
    for r in sorted(report.loans, key=lambda x: x.row_index):
        if r.verdict == "normal" and any(f.severity != "info" for f in r.findings):
            lines.append(f"- {r.loan_id}: {r.primary_reason}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tape", type=Path)
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--clean", type=int, nargs="*", default=[], help="known-clean loan IDs")
    parser.add_argument("--seeded", type=int, nargs="*", default=[], help="known-anomalous IDs")
    parser.add_argument("--max-share", type=float, default=0.40)
    parser.add_argument("--markdown", type=Path, default=None, help="also write a .md report")
    args = parser.parse_args()

    if not math.isfinite(args.max_share) or not 0 <= args.max_share <= 1:
        print("error: max-share must be a finite fraction between 0 and 1", file=sys.stderr)
        return 2
    try:
        config = Config.load(args.config)
        rules = [r for r in all_rules() if r.id not in config.disabled_rules]
        report = run(args.tape, config, rules=rules)
    except (ConfigError, TapeReadError, AsOfError, TapeRejectedError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    stats = admit(report, set(args.clean), args.max_share, rules)
    invalid: list[str] = []
    if not report.schema_ok:
        invalid.append("tape schema rejected")
    if not report.loans:
        invalid.append("no usable loans; tape rejected")
    if not rules:
        invalid.append("no intended rules enabled")
    by_id = {loan.loan_id: loan for loan in report.loans}
    absent = sorted((set(args.clean) | set(args.seeded)) - by_id.keys())
    if absent:
        invalid.append(f"calibration loan IDs absent or quarantined: {absent}")
    if set(args.clean) & set(args.seeded):
        invalid.append("clean and seeded calibration IDs must not overlap")
    if any(loan.checks_passed + loan.checks_failed == 0 for loan in report.loans):
        invalid.append("one or more loans had no evaluated rules")
    if any(s.fail + s.passed + s.not_evaluable != len(report.loans) for s in stats):
        invalid.append("intended rule outcomes missing")
    if any(by_id[i].validation_coverage != "full" for i in args.clean if i in by_id):
        invalid.append("known-clean calibration evidence is incomplete")

    print(f"{'rule':<5} {'fail':>5} {'pass':>5} {'n/e':>5} {'share':>6}  verdict")
    n = len(report.loans) or 1
    problems = sum(s.rejected for s in stats) + len(invalid)
    for problem in invalid:
        print(f"REJECTED: {problem}")
    for s in stats:
        counts = f"{s.fail:>5} {s.passed:>5} {s.not_evaluable:>5} {s.fail / n:>6.0%}"
        print(f"{s.rule.id:<5} {counts}  {s.verdict}")
    flagged_ids = {r.loan_id for r in report.loans if r.verdict == "flagged"}
    missed = sorted(set(args.seeded) - flagged_ids)
    if missed:
        problems += 1
        print(f"\nSEEDED LOANS NOT FLAGGED: {missed}")
    print()
    print(
        f"loans={len(report.loans)} quarantined={len(report.quarantined)} "
        f"flagged={len(flagged_ids)} problems={problems}"
    )
    if args.markdown:
        write_markdown(args.markdown, report, stats, args.clean, args.seeded)
        print(f"markdown written to {args.markdown}")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
